import express from'express';import cors from'cors';import bcrypt from'bcryptjs';import jwt from'jsonwebtoken';import path from'node:path';import{fileURLToPath}from'node:url';import{db,publicPlayer}from'./db.js';
const app=express(),SECRET=process.env.JWT_SECRET||'dev-only-change-me';app.use(cors());app.use(express.json());
type Req=express.Request&{playerId?:number};function auth(req:Req,res:express.Response,next:express.NextFunction){try{const raw=req.headers.authorization?.replace('Bearer ','');if(!raw)throw 0;req.playerId=+(jwt.verify(raw,SECRET)as any).id;next()}catch{res.status(401).json({error:'Please sign in again'})}}
const player=(id:number)=>db.prepare('SELECT * FROM players WHERE id=?').get(id)as any;const token=(id:number)=>jwt.sign({id},SECRET,{expiresIn:'14d'});
app.post('/api/signup',async(req,res)=>{const{username,password}=req.body;if(!username||username.length<3||!password||password.length<6)return res.status(400).json({error:'Use 3+ characters for username and 6+ for password'});try{const hash=await bcrypt.hash(password,12);const x=db.prepare('INSERT INTO players(username,password) VALUES(?,?)').run(username.trim(),hash);const p=player(Number(x.lastInsertRowid));res.status(201).json({token:token(p.id),player:publicPlayer(p)})}catch{res.status(409).json({error:'That username is already on the court'})}});
app.post('/api/login',async(req,res)=>{const p=db.prepare('SELECT * FROM players WHERE username=?').get(req.body.username?.trim())as any;if(!p||!await bcrypt.compare(req.body.password||'',p.password))return res.status(401).json({error:'Username or password is incorrect'});res.json({token:token(p.id),player:publicPlayer(p)})});
app.get('/api/player/me',auth,(req:Req,res)=>res.json(publicPlayer(player(req.playerId!))));app.get('/api/player/:id',auth,(req,res)=>{const p=player(+req.params.id);p?res.json(publicPlayer(p)):res.status(404).json({error:'Player not found'})});
app.post('/api/tutorial/complete',auth,(req:Req,res)=>{db.prepare('UPDATE players SET tutorialDone=1 WHERE id=?').run(req.playerId);res.json(publicPlayer(player(req.playerId!)))});
app.post('/api/avatar/update',auth,(req:Req,res)=>{const{hair='fade',height=6.4,clothing='purple',build='Athletic'}=req.body;db.prepare('UPDATE players SET hair=?,height=?,clothing=?,build=? WHERE id=?').run(hair,Math.max(5.6,Math.min(7.2,+height)),clothing,build,req.playerId);res.json(publicPlayer(player(req.playerId!)))});
app.post('/api/match/start',auth,(_req,res)=>{const op=db.prepare('SELECT * FROM opponents ORDER BY RANDOM() LIMIT 1').get();res.json({opponent:op})});
app.post('/api/match/end',auth,(req:Req,res)=>{const{opponentId,result,score}=req.body;if(!['win','loss'].includes(result))return res.status(400).json({error:'Invalid result'});const earned=result==='win'?500:0;db.transaction(()=>{db.prepare('INSERT INTO matches(playerId,opponentId,result,score) VALUES(?,?,?,?)').run(req.playerId,opponentId,result,String(score));db.prepare(`UPDATE players SET gamesPlayed=gamesPlayed+1,playoffGames=playoffGames+1,coins=coins+?,wins=wins+?,losses=losses+? WHERE id=?`).run(earned,result==='win'?1:0,result==='loss'?1:0,req.playerId)})();res.json({player:publicPlayer(player(req.playerId!)),coinsEarned:earned})});
app.post('/api/shop/buy',auth,(req:Req,res)=>{const{item,cost}=req.body;const p=player(req.playerId!);if(!Number.isInteger(cost)||cost<0||p.coins<cost)return res.status(400).json({error:'Not enough coins'});const[type,value]=String(item).split(':');if(!['hair','clothing'].includes(type))return res.status(400).json({error:'Invalid shop item'});db.transaction(()=>{db.prepare('UPDATE players SET coins=coins-? WHERE id=?').run(cost,req.playerId);db.prepare('INSERT OR IGNORE INTO inventory(playerId,item) VALUES(?,?)').run(req.playerId,item);db.prepare(`UPDATE players SET ${type}=? WHERE id=?`).run(value,req.playerId)})();res.json(publicPlayer(player(req.playerId!)))});
function bracket(){const names=(db.prepare('SELECT name FROM opponents ORDER BY RANDOM() LIMIT 8').all()as any[]).map(x=>x.name);return{rounds:[{name:'1ST ROUND',games:[[names[0],names[1]],[names[2],names[3]],[names[4],names[5]],[names[6],names[7]]].map(x=>({a:x[0],b:x[1],aWins:0,bWins:0}))},{name:'2ND ROUND',games:[{a:'TBD',b:'TBD',aWins:0,bWins:0},{a:'TBD',b:'TBD',aWins:0,bWins:0}]},{name:'CONFERENCE FINALS',games:[{a:'TBD',b:'TBD',aWins:0,bWins:0}]},{name:'FINALS',games:[{a:'YOU',b:'TBD',aWins:0,bWins:0}]},{name:'3RD PLACE',games:[{a:'TBD',b:'TBD',aWins:0,bWins:0}]}]}}
app.get('/api/playoffs/bracket',auth,(_req,res)=>res.json(bracket()));app.post('/api/playoffs/start',auth,(req:Req,res)=>{const p=player(req.playerId!);if(p.playoffGames<5)return res.status(403).json({error:`Playoffs unlock after ${5-p.playoffGames} more games`});const odds:{[k:string]:number}={Rookie:.9,Pro:.72,'All-Star':.55,'Hall of Fame':.38};const champion=Math.random()<(odds[req.body.difficulty]??.72);let reward=0;if(champion){reward=(p.championshipsWon+1)*5000;db.prepare('UPDATE players SET championshipsWon=championshipsWon+1,playoffGames=0,coins=coins+?,difficulty=? WHERE id=?').run(reward,req.body.difficulty,req.playerId)}const b=bracket();b.rounds.forEach((r:any)=>r.games.forEach((g:any)=>{g.aWins=champion?3:Math.floor(Math.random()*3);g.bWins=champion?Math.floor(Math.random()*3):3}));res.json({champion,reward,bracket:b,player:publicPlayer(player(req.playerId!))})});
const here=path.dirname(fileURLToPath(import.meta.url)),client=path.join(here,'../../client/dist');app.use(express.static(client));app.get('/{*splat}',(req,res,next)=>req.path.startsWith('/api')?next():res.sendFile(path.join(client,'index.html')));const port=+(process.env.PORT||3001);app.listen(port,()=>console.log(`Dasketball API on ${port}`));
